version: "3.9"

services:
  telegramBot:
    container_name: "telegram-bot"
    build: .
    restart: always
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data

volumes:
  data: {}